/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateTestRouteImport } from './routes/create-test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as RunRunIdRouteImport } from './routes/run.$runId'
import { Route as ProjectProjectSlugRouteImport } from './routes/project.$projectSlug'
import { Route as EditTestTestIdRouteImport } from './routes/edit-test.$testId'
import { Route as ProjectProjectSlugRunsRouteImport } from './routes/project.$projectSlug.runs'
import { Route as ProjectProjectSlugRepositoryRouteImport } from './routes/project.$projectSlug.repository'
import { Route as ProjectProjectSlugReportsRouteImport } from './routes/project.$projectSlug.reports'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTestRoute = CreateTestRouteImport.update({
  id: '/create-test',
  path: '/create-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdRoute = RunRunIdRouteImport.update({
  id: '/run/$runId',
  path: '/run/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectSlugRoute = ProjectProjectSlugRouteImport.update({
  id: '/project/$projectSlug',
  path: '/project/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTestTestIdRoute = EditTestTestIdRouteImport.update({
  id: '/edit-test/$testId',
  path: '/edit-test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectSlugRunsRoute = ProjectProjectSlugRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ProjectProjectSlugRoute,
} as any)
const ProjectProjectSlugRepositoryRoute =
  ProjectProjectSlugRepositoryRouteImport.update({
    id: '/repository',
    path: '/repository',
    getParentRoute: () => ProjectProjectSlugRoute,
  } as any)
const ProjectProjectSlugReportsRoute =
  ProjectProjectSlugReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProjectProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-test': typeof CreateTestRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit-test/$testId': typeof EditTestTestIdRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRouteWithChildren
  '/run/$runId': typeof RunRunIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/project/$projectSlug/reports': typeof ProjectProjectSlugReportsRoute
  '/project/$projectSlug/repository': typeof ProjectProjectSlugRepositoryRoute
  '/project/$projectSlug/runs': typeof ProjectProjectSlugRunsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-test': typeof CreateTestRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit-test/$testId': typeof EditTestTestIdRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRouteWithChildren
  '/run/$runId': typeof RunRunIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/project/$projectSlug/reports': typeof ProjectProjectSlugReportsRoute
  '/project/$projectSlug/repository': typeof ProjectProjectSlugRepositoryRoute
  '/project/$projectSlug/runs': typeof ProjectProjectSlugRunsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-test': typeof CreateTestRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit-test/$testId': typeof EditTestTestIdRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRouteWithChildren
  '/run/$runId': typeof RunRunIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/project/$projectSlug/reports': typeof ProjectProjectSlugReportsRoute
  '/project/$projectSlug/repository': typeof ProjectProjectSlugRepositoryRoute
  '/project/$projectSlug/runs': typeof ProjectProjectSlugRunsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create-test'
    | '/login'
    | '/register'
    | '/edit-test/$testId'
    | '/project/$projectSlug'
    | '/run/$runId'
    | '/test/$testId'
    | '/project/$projectSlug/reports'
    | '/project/$projectSlug/repository'
    | '/project/$projectSlug/runs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create-test'
    | '/login'
    | '/register'
    | '/edit-test/$testId'
    | '/project/$projectSlug'
    | '/run/$runId'
    | '/test/$testId'
    | '/project/$projectSlug/reports'
    | '/project/$projectSlug/repository'
    | '/project/$projectSlug/runs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create-test'
    | '/login'
    | '/register'
    | '/edit-test/$testId'
    | '/project/$projectSlug'
    | '/run/$runId'
    | '/test/$testId'
    | '/project/$projectSlug/reports'
    | '/project/$projectSlug/repository'
    | '/project/$projectSlug/runs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateTestRoute: typeof CreateTestRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EditTestTestIdRoute: typeof EditTestTestIdRoute
  ProjectProjectSlugRoute: typeof ProjectProjectSlugRouteWithChildren
  RunRunIdRoute: typeof RunRunIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-test': {
      id: '/create-test'
      path: '/create-test'
      fullPath: '/create-test'
      preLoaderRoute: typeof CreateTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId': {
      id: '/run/$runId'
      path: '/run/$runId'
      fullPath: '/run/$runId'
      preLoaderRoute: typeof RunRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug': {
      id: '/project/$projectSlug'
      path: '/project/$projectSlug'
      fullPath: '/project/$projectSlug'
      preLoaderRoute: typeof ProjectProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-test/$testId': {
      id: '/edit-test/$testId'
      path: '/edit-test/$testId'
      fullPath: '/edit-test/$testId'
      preLoaderRoute: typeof EditTestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug/runs': {
      id: '/project/$projectSlug/runs'
      path: '/runs'
      fullPath: '/project/$projectSlug/runs'
      preLoaderRoute: typeof ProjectProjectSlugRunsRouteImport
      parentRoute: typeof ProjectProjectSlugRoute
    }
    '/project/$projectSlug/repository': {
      id: '/project/$projectSlug/repository'
      path: '/repository'
      fullPath: '/project/$projectSlug/repository'
      preLoaderRoute: typeof ProjectProjectSlugRepositoryRouteImport
      parentRoute: typeof ProjectProjectSlugRoute
    }
    '/project/$projectSlug/reports': {
      id: '/project/$projectSlug/reports'
      path: '/reports'
      fullPath: '/project/$projectSlug/reports'
      preLoaderRoute: typeof ProjectProjectSlugReportsRouteImport
      parentRoute: typeof ProjectProjectSlugRoute
    }
  }
}

interface ProjectProjectSlugRouteChildren {
  ProjectProjectSlugReportsRoute: typeof ProjectProjectSlugReportsRoute
  ProjectProjectSlugRepositoryRoute: typeof ProjectProjectSlugRepositoryRoute
  ProjectProjectSlugRunsRoute: typeof ProjectProjectSlugRunsRoute
}

const ProjectProjectSlugRouteChildren: ProjectProjectSlugRouteChildren = {
  ProjectProjectSlugReportsRoute: ProjectProjectSlugReportsRoute,
  ProjectProjectSlugRepositoryRoute: ProjectProjectSlugRepositoryRoute,
  ProjectProjectSlugRunsRoute: ProjectProjectSlugRunsRoute,
}

const ProjectProjectSlugRouteWithChildren =
  ProjectProjectSlugRoute._addFileChildren(ProjectProjectSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateTestRoute: CreateTestRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EditTestTestIdRoute: EditTestTestIdRoute,
  ProjectProjectSlugRoute: ProjectProjectSlugRouteWithChildren,
  RunRunIdRoute: RunRunIdRoute,
  TestTestIdRoute: TestTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
