/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreateTestRouteImport } from './routes/create-test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as RunRunIdRouteImport } from './routes/run.$runId'
import { Route as ProjectProjectSlugRouteImport } from './routes/project.$projectSlug'
import { Route as EditTestTestIdRouteImport } from './routes/edit-test.$testId'
import { Route as ProjectProjectSlugRepositoryRouteImport } from './routes/project_.$projectSlug.repository'
import { Route as ProjectProjectSlugRunsRouteImport } from './routes/project.$projectSlug.runs'
import { Route as ProjectProjectSlugReportsRouteImport } from './routes/project.$projectSlug.reports'
import { Route as ProjectProjectSlugDocsRouteImport } from './routes/project.$projectSlug.docs'
import { Route as ProjectProjectSlugAutomationRouteImport } from './routes/project.$projectSlug.automation'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectProjectSlugDocsDocIdRouteImport } from './routes/project_.$projectSlug.docs_.$docId'
import { Route as ProjectProjectSlugAutomationRunsRouteImport } from './routes/project.$projectSlug.automation.runs'
import { Route as ApiProjectsProjectIdAutomationRunsRouteImport } from './routes/api/projects.$projectId.automation-runs'
import { Route as ProjectProjectSlugAutomationRunsRunIdRouteImport } from './routes/project.$projectSlug.automation.runs.$runId'
import { Route as ApiProjectsProjectIdAutomationRunsImportJunitRouteImport } from './routes/api/projects.$projectId.automation-runs.import.junit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTestRoute = CreateTestRouteImport.update({
  id: '/create-test',
  path: '/create-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdRoute = RunRunIdRouteImport.update({
  id: '/run/$runId',
  path: '/run/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectSlugRoute = ProjectProjectSlugRouteImport.update({
  id: '/project/$projectSlug',
  path: '/project/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTestTestIdRoute = EditTestTestIdRouteImport.update({
  id: '/edit-test/$testId',
  path: '/edit-test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectSlugRepositoryRoute =
  ProjectProjectSlugRepositoryRouteImport.update({
    id: '/project_/$projectSlug/repository',
    path: '/project/$projectSlug/repository',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectSlugRunsRoute = ProjectProjectSlugRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ProjectProjectSlugRoute,
} as any)
const ProjectProjectSlugReportsRoute =
  ProjectProjectSlugReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProjectProjectSlugRoute,
  } as any)
const ProjectProjectSlugDocsRoute = ProjectProjectSlugDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ProjectProjectSlugRoute,
} as any)
const ProjectProjectSlugAutomationRoute =
  ProjectProjectSlugAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => ProjectProjectSlugRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectSlugDocsDocIdRoute =
  ProjectProjectSlugDocsDocIdRouteImport.update({
    id: '/project_/$projectSlug/docs_/$docId',
    path: '/project/$projectSlug/docs/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectSlugAutomationRunsRoute =
  ProjectProjectSlugAutomationRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => ProjectProjectSlugAutomationRoute,
  } as any)
const ApiProjectsProjectIdAutomationRunsRoute =
  ApiProjectsProjectIdAutomationRunsRouteImport.update({
    id: '/api/projects/$projectId/automation-runs',
    path: '/api/projects/$projectId/automation-runs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectSlugAutomationRunsRunIdRoute =
  ProjectProjectSlugAutomationRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => ProjectProjectSlugAutomationRunsRoute,
  } as any)
const ApiProjectsProjectIdAutomationRunsImportJunitRoute =
  ApiProjectsProjectIdAutomationRunsImportJunitRouteImport.update({
    id: '/import/junit',
    path: '/import/junit',
    getParentRoute: () => ApiProjectsProjectIdAutomationRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-test': typeof CreateTestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/edit-test/$testId': typeof EditTestTestIdRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRouteWithChildren
  '/run/$runId': typeof RunRunIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectSlug/automation': typeof ProjectProjectSlugAutomationRouteWithChildren
  '/project/$projectSlug/docs': typeof ProjectProjectSlugDocsRoute
  '/project/$projectSlug/reports': typeof ProjectProjectSlugReportsRoute
  '/project/$projectSlug/runs': typeof ProjectProjectSlugRunsRoute
  '/project/$projectSlug/repository': typeof ProjectProjectSlugRepositoryRoute
  '/api/projects/$projectId/automation-runs': typeof ApiProjectsProjectIdAutomationRunsRouteWithChildren
  '/project/$projectSlug/automation/runs': typeof ProjectProjectSlugAutomationRunsRouteWithChildren
  '/project/$projectSlug/docs/$docId': typeof ProjectProjectSlugDocsDocIdRoute
  '/project/$projectSlug/automation/runs/$runId': typeof ProjectProjectSlugAutomationRunsRunIdRoute
  '/api/projects/$projectId/automation-runs/import/junit': typeof ApiProjectsProjectIdAutomationRunsImportJunitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-test': typeof CreateTestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/edit-test/$testId': typeof EditTestTestIdRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRouteWithChildren
  '/run/$runId': typeof RunRunIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectSlug/automation': typeof ProjectProjectSlugAutomationRouteWithChildren
  '/project/$projectSlug/docs': typeof ProjectProjectSlugDocsRoute
  '/project/$projectSlug/reports': typeof ProjectProjectSlugReportsRoute
  '/project/$projectSlug/runs': typeof ProjectProjectSlugRunsRoute
  '/project/$projectSlug/repository': typeof ProjectProjectSlugRepositoryRoute
  '/api/projects/$projectId/automation-runs': typeof ApiProjectsProjectIdAutomationRunsRouteWithChildren
  '/project/$projectSlug/automation/runs': typeof ProjectProjectSlugAutomationRunsRouteWithChildren
  '/project/$projectSlug/docs/$docId': typeof ProjectProjectSlugDocsDocIdRoute
  '/project/$projectSlug/automation/runs/$runId': typeof ProjectProjectSlugAutomationRunsRunIdRoute
  '/api/projects/$projectId/automation-runs/import/junit': typeof ApiProjectsProjectIdAutomationRunsImportJunitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-test': typeof CreateTestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/edit-test/$testId': typeof EditTestTestIdRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRouteWithChildren
  '/run/$runId': typeof RunRunIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectSlug/automation': typeof ProjectProjectSlugAutomationRouteWithChildren
  '/project/$projectSlug/docs': typeof ProjectProjectSlugDocsRoute
  '/project/$projectSlug/reports': typeof ProjectProjectSlugReportsRoute
  '/project/$projectSlug/runs': typeof ProjectProjectSlugRunsRoute
  '/project_/$projectSlug/repository': typeof ProjectProjectSlugRepositoryRoute
  '/api/projects/$projectId/automation-runs': typeof ApiProjectsProjectIdAutomationRunsRouteWithChildren
  '/project/$projectSlug/automation/runs': typeof ProjectProjectSlugAutomationRunsRouteWithChildren
  '/project_/$projectSlug/docs_/$docId': typeof ProjectProjectSlugDocsDocIdRoute
  '/project/$projectSlug/automation/runs/$runId': typeof ProjectProjectSlugAutomationRunsRunIdRoute
  '/api/projects/$projectId/automation-runs/import/junit': typeof ApiProjectsProjectIdAutomationRunsImportJunitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create-test'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/edit-test/$testId'
    | '/project/$projectSlug'
    | '/run/$runId'
    | '/test/$testId'
    | '/api/auth/$'
    | '/project/$projectSlug/automation'
    | '/project/$projectSlug/docs'
    | '/project/$projectSlug/reports'
    | '/project/$projectSlug/runs'
    | '/project/$projectSlug/repository'
    | '/api/projects/$projectId/automation-runs'
    | '/project/$projectSlug/automation/runs'
    | '/project/$projectSlug/docs/$docId'
    | '/project/$projectSlug/automation/runs/$runId'
    | '/api/projects/$projectId/automation-runs/import/junit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create-test'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/edit-test/$testId'
    | '/project/$projectSlug'
    | '/run/$runId'
    | '/test/$testId'
    | '/api/auth/$'
    | '/project/$projectSlug/automation'
    | '/project/$projectSlug/docs'
    | '/project/$projectSlug/reports'
    | '/project/$projectSlug/runs'
    | '/project/$projectSlug/repository'
    | '/api/projects/$projectId/automation-runs'
    | '/project/$projectSlug/automation/runs'
    | '/project/$projectSlug/docs/$docId'
    | '/project/$projectSlug/automation/runs/$runId'
    | '/api/projects/$projectId/automation-runs/import/junit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create-test'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/edit-test/$testId'
    | '/project/$projectSlug'
    | '/run/$runId'
    | '/test/$testId'
    | '/api/auth/$'
    | '/project/$projectSlug/automation'
    | '/project/$projectSlug/docs'
    | '/project/$projectSlug/reports'
    | '/project/$projectSlug/runs'
    | '/project_/$projectSlug/repository'
    | '/api/projects/$projectId/automation-runs'
    | '/project/$projectSlug/automation/runs'
    | '/project_/$projectSlug/docs_/$docId'
    | '/project/$projectSlug/automation/runs/$runId'
    | '/api/projects/$projectId/automation-runs/import/junit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateTestRoute: typeof CreateTestRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EditTestTestIdRoute: typeof EditTestTestIdRoute
  ProjectProjectSlugRoute: typeof ProjectProjectSlugRouteWithChildren
  RunRunIdRoute: typeof RunRunIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProjectProjectSlugRepositoryRoute: typeof ProjectProjectSlugRepositoryRoute
  ApiProjectsProjectIdAutomationRunsRoute: typeof ApiProjectsProjectIdAutomationRunsRouteWithChildren
  ProjectProjectSlugDocsDocIdRoute: typeof ProjectProjectSlugDocsDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-test': {
      id: '/create-test'
      path: '/create-test'
      fullPath: '/create-test'
      preLoaderRoute: typeof CreateTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId': {
      id: '/run/$runId'
      path: '/run/$runId'
      fullPath: '/run/$runId'
      preLoaderRoute: typeof RunRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug': {
      id: '/project/$projectSlug'
      path: '/project/$projectSlug'
      fullPath: '/project/$projectSlug'
      preLoaderRoute: typeof ProjectProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-test/$testId': {
      id: '/edit-test/$testId'
      path: '/edit-test/$testId'
      fullPath: '/edit-test/$testId'
      preLoaderRoute: typeof EditTestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project_/$projectSlug/repository': {
      id: '/project_/$projectSlug/repository'
      path: '/project/$projectSlug/repository'
      fullPath: '/project/$projectSlug/repository'
      preLoaderRoute: typeof ProjectProjectSlugRepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug/runs': {
      id: '/project/$projectSlug/runs'
      path: '/runs'
      fullPath: '/project/$projectSlug/runs'
      preLoaderRoute: typeof ProjectProjectSlugRunsRouteImport
      parentRoute: typeof ProjectProjectSlugRoute
    }
    '/project/$projectSlug/reports': {
      id: '/project/$projectSlug/reports'
      path: '/reports'
      fullPath: '/project/$projectSlug/reports'
      preLoaderRoute: typeof ProjectProjectSlugReportsRouteImport
      parentRoute: typeof ProjectProjectSlugRoute
    }
    '/project/$projectSlug/docs': {
      id: '/project/$projectSlug/docs'
      path: '/docs'
      fullPath: '/project/$projectSlug/docs'
      preLoaderRoute: typeof ProjectProjectSlugDocsRouteImport
      parentRoute: typeof ProjectProjectSlugRoute
    }
    '/project/$projectSlug/automation': {
      id: '/project/$projectSlug/automation'
      path: '/automation'
      fullPath: '/project/$projectSlug/automation'
      preLoaderRoute: typeof ProjectProjectSlugAutomationRouteImport
      parentRoute: typeof ProjectProjectSlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project_/$projectSlug/docs_/$docId': {
      id: '/project_/$projectSlug/docs_/$docId'
      path: '/project/$projectSlug/docs/$docId'
      fullPath: '/project/$projectSlug/docs/$docId'
      preLoaderRoute: typeof ProjectProjectSlugDocsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug/automation/runs': {
      id: '/project/$projectSlug/automation/runs'
      path: '/runs'
      fullPath: '/project/$projectSlug/automation/runs'
      preLoaderRoute: typeof ProjectProjectSlugAutomationRunsRouteImport
      parentRoute: typeof ProjectProjectSlugAutomationRoute
    }
    '/api/projects/$projectId/automation-runs': {
      id: '/api/projects/$projectId/automation-runs'
      path: '/api/projects/$projectId/automation-runs'
      fullPath: '/api/projects/$projectId/automation-runs'
      preLoaderRoute: typeof ApiProjectsProjectIdAutomationRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug/automation/runs/$runId': {
      id: '/project/$projectSlug/automation/runs/$runId'
      path: '/$runId'
      fullPath: '/project/$projectSlug/automation/runs/$runId'
      preLoaderRoute: typeof ProjectProjectSlugAutomationRunsRunIdRouteImport
      parentRoute: typeof ProjectProjectSlugAutomationRunsRoute
    }
    '/api/projects/$projectId/automation-runs/import/junit': {
      id: '/api/projects/$projectId/automation-runs/import/junit'
      path: '/import/junit'
      fullPath: '/api/projects/$projectId/automation-runs/import/junit'
      preLoaderRoute: typeof ApiProjectsProjectIdAutomationRunsImportJunitRouteImport
      parentRoute: typeof ApiProjectsProjectIdAutomationRunsRoute
    }
  }
}

interface ProjectProjectSlugAutomationRunsRouteChildren {
  ProjectProjectSlugAutomationRunsRunIdRoute: typeof ProjectProjectSlugAutomationRunsRunIdRoute
}

const ProjectProjectSlugAutomationRunsRouteChildren: ProjectProjectSlugAutomationRunsRouteChildren =
  {
    ProjectProjectSlugAutomationRunsRunIdRoute:
      ProjectProjectSlugAutomationRunsRunIdRoute,
  }

const ProjectProjectSlugAutomationRunsRouteWithChildren =
  ProjectProjectSlugAutomationRunsRoute._addFileChildren(
    ProjectProjectSlugAutomationRunsRouteChildren,
  )

interface ProjectProjectSlugAutomationRouteChildren {
  ProjectProjectSlugAutomationRunsRoute: typeof ProjectProjectSlugAutomationRunsRouteWithChildren
}

const ProjectProjectSlugAutomationRouteChildren: ProjectProjectSlugAutomationRouteChildren =
  {
    ProjectProjectSlugAutomationRunsRoute:
      ProjectProjectSlugAutomationRunsRouteWithChildren,
  }

const ProjectProjectSlugAutomationRouteWithChildren =
  ProjectProjectSlugAutomationRoute._addFileChildren(
    ProjectProjectSlugAutomationRouteChildren,
  )

interface ProjectProjectSlugRouteChildren {
  ProjectProjectSlugAutomationRoute: typeof ProjectProjectSlugAutomationRouteWithChildren
  ProjectProjectSlugDocsRoute: typeof ProjectProjectSlugDocsRoute
  ProjectProjectSlugReportsRoute: typeof ProjectProjectSlugReportsRoute
  ProjectProjectSlugRunsRoute: typeof ProjectProjectSlugRunsRoute
}

const ProjectProjectSlugRouteChildren: ProjectProjectSlugRouteChildren = {
  ProjectProjectSlugAutomationRoute:
    ProjectProjectSlugAutomationRouteWithChildren,
  ProjectProjectSlugDocsRoute: ProjectProjectSlugDocsRoute,
  ProjectProjectSlugReportsRoute: ProjectProjectSlugReportsRoute,
  ProjectProjectSlugRunsRoute: ProjectProjectSlugRunsRoute,
}

const ProjectProjectSlugRouteWithChildren =
  ProjectProjectSlugRoute._addFileChildren(ProjectProjectSlugRouteChildren)

interface ApiProjectsProjectIdAutomationRunsRouteChildren {
  ApiProjectsProjectIdAutomationRunsImportJunitRoute: typeof ApiProjectsProjectIdAutomationRunsImportJunitRoute
}

const ApiProjectsProjectIdAutomationRunsRouteChildren: ApiProjectsProjectIdAutomationRunsRouteChildren =
  {
    ApiProjectsProjectIdAutomationRunsImportJunitRoute:
      ApiProjectsProjectIdAutomationRunsImportJunitRoute,
  }

const ApiProjectsProjectIdAutomationRunsRouteWithChildren =
  ApiProjectsProjectIdAutomationRunsRoute._addFileChildren(
    ApiProjectsProjectIdAutomationRunsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateTestRoute: CreateTestRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EditTestTestIdRoute: EditTestTestIdRoute,
  ProjectProjectSlugRoute: ProjectProjectSlugRouteWithChildren,
  RunRunIdRoute: RunRunIdRoute,
  TestTestIdRoute: TestTestIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProjectProjectSlugRepositoryRoute: ProjectProjectSlugRepositoryRoute,
  ApiProjectsProjectIdAutomationRunsRoute:
    ApiProjectsProjectIdAutomationRunsRouteWithChildren,
  ProjectProjectSlugDocsDocIdRoute: ProjectProjectSlugDocsDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
